-- Cases measures — Contact Center KPI Dashboard

Total Cases =
COUNTROWS ( 'cases' )

Closed Cases =
CALCULATE ( [Total Cases], 'cases'[status] = "closed" )

FCR Cases =
CALCULATE ( [Closed Cases], 'cases'[resolution_type] = "FCR" )

FCR Rate =
DIVIDE ( [FCR Cases], [Closed Cases] )

Cases In SLA =
CALCULATE ( [Closed Cases], 'cases'[resolved_in_sla] = TRUE () )

Cases Past SLA =
CALCULATE ( [Closed Cases], 'cases'[resolved_in_sla] = FALSE () )

SLA Rate =
DIVIDE ( [Cases In SLA], [Closed Cases] )

Escalated Cases =
CALCULATE ( [Total Cases], 'cases'[is_escalated_to_2nd_line] = TRUE () )

Escalation Rate =
DIVIDE ( [Escalated Cases], [Total Cases] )

Average Resolution Time Hours =
AVERAGEX (
    FILTER ( 'cases', NOT ISBLANK ( 'cases'[closed_at] ) ),
    DATEDIFF ( 'cases'[opened_at], 'cases'[closed_at], HOUR )
)

High Priority Cases =
CALCULATE ( [Total Cases], 'cases'[priority] IN { "high", "critical" } )
