-- Calls measures — Contact Center KPI Dashboard

Total Calls =
COUNTROWS ( 'calls' )

Inbound Calls =
CALCULATE ( [Total Calls], 'calls'[direction] = "inbound" )

Outbound Calls =
CALCULATE ( [Total Calls], 'calls'[direction] = "outbound" )

Answered Calls =
CALCULATE ( [Total Calls], 'calls'[is_answered_by_agent] = TRUE () )

Abandoned Calls =
CALCULATE ( [Total Calls], 'calls'[is_abandoned_in_queue] = TRUE () )

Self-service Calls =
CALCULATE ( [Total Calls], 'calls'[is_self_service] = TRUE () )

ASA Seconds =
AVERAGEX (
    FILTER (
        'calls',
        'calls'[direction] = "inbound"
            && 'calls'[is_answered_by_agent] = TRUE ()
            && NOT ISBLANK ( 'calls'[queue_start_time] )
            && NOT ISBLANK ( 'calls'[answer_time] )
    ),
    DATEDIFF ( 'calls'[queue_start_time], 'calls'[answer_time], SECOND )
)

AHT Seconds =
AVERAGEX (
    FILTER (
        'calls',
        'calls'[is_answered_by_agent] = TRUE ()
            && NOT ISBLANK ( 'calls'[answer_time] )
            && NOT ISBLANK ( 'calls'[end_time] )
    ),
    DATEDIFF ( 'calls'[answer_time], 'calls'[end_time], SECOND )
)

Abandonment Rate =
DIVIDE ( [Abandoned Calls], [Inbound Calls] )

Self-service Rate =
DIVIDE ( [Self-service Calls], [Inbound Calls] )

Answered Rate =
DIVIDE ( [Answered Calls], [Inbound Calls] )

Call Volume YoY =
VAR CurrentCalls = [Total Calls]
VAR PreviousCalls = CALCULATE ( [Total Calls], SAMEPERIODLASTYEAR ( 'Date'[Date] ) )
RETURN
DIVIDE ( CurrentCalls - PreviousCalls, PreviousCalls )
