-- Alert measures — Contact Center KPI Dashboard

Operational Exceptions =
[Cases Past SLA] + [Failed Callbacks] + [Overdue Callbacks]

SLA Alert Flag =
IF ( [SLA Rate] < 0.90, 1, 0 )

Callback Alert Flag =
IF ( [Callback Realization Rate] < 0.85, 1, 0 )

Abandonment Alert Flag =
IF ( [Abandonment Rate] > 0.12, 1, 0 )

ASA Alert Flag =
IF ( [ASA Seconds] > 120, 1, 0 )

Executive Health Score =
VAR SlaScore = MIN ( 1, [SLA Rate] / 0.95 )
VAR CallbackScore = MIN ( 1, [Callback Realization Rate] / 0.90 )
VAR AbandonmentScore = MAX ( 0, 1 - DIVIDE ( [Abandonment Rate], 0.20 ) )
VAR AsaScore = MAX ( 0, 1 - DIVIDE ( [ASA Seconds], 240 ) )
RETURN
ROUND ( 100 * AVERAGEX ( { SlaScore, CallbackScore, AbandonmentScore, AsaScore }, [Value] ), 0 )
